# Generated by Django 6.0.3 on 2026-03-12 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('finance', '0002_alter_financialmovement_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='financialmovement',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='movementcategory',
            unique_together={('client', 'name', 'type')},
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='is_reconciled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='is_recurrent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='movement_type',
            field=models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso')], db_index=True, default='expense', max_length=10),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('transfer', 'Transferencia'), ('check', 'Cheque'), ('credit_card', 'Tarjeta de Credito'), ('debit_card', 'Tarjeta de Debito'), ('bizum', 'Bizum')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='financialmovement',
            name='receipt_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='movementcategory',
            name='color',
            field=models.CharField(blank=True, max_length=7),
        ),
        migrations.AddField(
            model_name='movementcategory',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='financialmovement',
            name='receipt',
            field=models.FileField(blank=True, null=True, upload_to='finance/receipts/', verbose_name='Recibo'),
        ),
        migrations.AddIndex(
            model_name='financialmovement',
            index=models.Index(fields=['client', 'date'], name='finance_fin_client__c34748_idx'),
        ),
        migrations.AddIndex(
            model_name='financialmovement',
            index=models.Index(fields=['client', 'movement_type'], name='finance_fin_client__8d4b71_idx'),
        ),
        migrations.AddIndex(
            model_name='financialmovement',
            index=models.Index(fields=['client', 'category'], name='finance_fin_client__590d80_idx'),
        ),
    ]
