# Generated by Django 6.0.3 on 2026-03-13 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_financialmovement_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movementcategory',
            name='type',
            field=models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso'), ('investment', 'Inversión'), ('loan', 'Prestamo')], max_length=10),
        ),
    ]
