# Generated by Django 6.0.3 on 2026-03-13 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_movementcategory_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financialmovement',
            name='movement_type',
            field=models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso')], db_index=True, max_length=10),
        ),
    ]
