# Generated by Django 6.0.3 on 2026-03-20 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_financialmovement_movement_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialmovement',
            old_name='is_reconciled',
            new_name='is_conciled',
        ),
    ]
