# Generated by Django 6.0.3 on 2026-03-20 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_rename_is_reconciled_financialmovement_is_conciled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='financialmovement',
            old_name='is_conciled',
            new_name='is_reconciled',
        ),
    ]
