# Generated by Django 6.0.3 on 2026-03-05 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('prefix', models.CharField(db_index=True, max_length=32)),
                ('key_hash', models.CharField(max_length=128)),
                ('environment', models.CharField(choices=[('live', 'Live'), ('test', 'Test')], default='live', max_length=10)),
                ('scopes', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='clients.client')),
            ],
            options={
                'indexes': [models.Index(fields=['prefix', 'is_active'], name='api_apikey_prefix_3fde9a_idx')],
            },
        ),
    ]
