# Generated by Django 6.0.3 on 2026-03-05 00:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='clients.client'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['prefix', 'is_active'], name='api_apikey_prefix_3fde9a_idx'),
        ),
    ]
