# Generated by Django 6.0.1 on 2026-03-04 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apikey',
            name='key',
        ),
        migrations.AddField(
            model_name='apikey',
            name='environment',
            field=models.CharField(choices=[('live', 'Live'), ('test', 'Test')], default='live', max_length=10),
        ),
        migrations.AddField(
            model_name='apikey',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AddField(
            model_name='apikey',
            name='last_used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apikey',
            name='prefix',
            field=models.CharField(db_index=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='apikey',
            name='scopes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='clients.client'),
        ),
        migrations.AddIndex(
            model_name='apikey',
            index=models.Index(fields=['prefix', 'is_active'], name='api_apikey_prefix_3fde9a_idx'),
        ),
    ]
