# Generated by Django 6.0.1 on 2026-03-04 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_apikey_key_apikey_environment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='prefix',
            field=models.CharField(db_index=True, default='', max_length=32),
        ),
    ]
