# Generated by Django 6.0.1 on 2026-03-04 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_apikey_prefix'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key_hash',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='prefix',
            field=models.CharField(db_index=True, max_length=32),
        ),
    ]
