# Generated by Django 6.0.3 on 2026-03-18 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clients/logos/'),
        ),
        migrations.AddField(
            model_name='client',
            name='primary_color',
            field=models.CharField(default='#2563eb', max_length=7),
        ),
    ]
