# Generated by Django 6.0.1 on 2026-01-27 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/')),
                ('original_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('invoice', 'Factura'), ('delivery', 'Albarán'), ('other', 'Otro')], max_length=20)),
                ('confidence', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pendientes'), ('approved', 'Aprobado'), ('needs_review', 'Revisión'), ('error', 'Error')], default='pending', max_length=20)),
                ('extracted_data', models.JSONField()),
                ('provider_name', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
