# Generated by Django 6.0.1 on 2026-02-10 01:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('tax_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('type', models.CharField(choices=[('provider', 'Proveedor'), ('customer', 'Cliente')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='clients.client')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, unique=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('original_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('invoice', 'Factura'), ('delivery', 'Albarán'), ('other', 'Otro')], max_length=20)),
                ('invoice_number', models.CharField(blank=True, max_length=255, null=True)),
                ('confidence', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='pending', max_length=20)),
                ('review_level', models.CharField(choices=[('auto', 'Aprovado automáticamente'), ('manual', 'Manual'), ('recommended', 'Revisión recomendada'), ('required', 'Revisión requerida')], default='required', max_length=20)),
                ('extracted_data', models.JSONField()),
                ('provider_name', models.CharField(blank=True, max_length=255, null=True)),
                ('provider_tax_id', models.CharField(blank=True, max_length=50, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tax_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_source', models.CharField(choices=[('explicit', 'Explicit'), ('base_tax', 'Base + Tax'), ('base', 'Base only'), ('unknown', 'Unknown')], default='unknown', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('flow', models.CharField(choices=[('in', 'Compra'), ('out', 'Venta'), ('unknown', 'Por revisar')], default='unknown', max_length=20)),
                ('flow_source', models.CharField(choices=[('auto', 'Automático'), ('manual', 'Manual')], default='auto', max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='clients.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
