# Generated by Django 6.0.1 on 2026-02-11 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='extracted_data',
        ),
        migrations.AlterField(
            model_name='document',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='documents.company'),
        ),
        migrations.AlterField(
            model_name='document',
            name='provider_name',
            field=models.CharField(default='Proveedor desconocido', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='provider_tax_id',
            field=models.CharField(default='N/A', max_length=50),
        ),
    ]
