# Generated by Django 6.0.1 on 2026-02-11 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_remove_document_extracted_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Factura'), ('delivery', 'Albarán'), ('corrected_invoice', 'Abono'), ('other', 'Otro')], max_length=20),
        ),
    ]
