# Generated by Django 6.0.1 on 2026-02-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('documents', '0003_alter_document_document_type'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('client', 'tax_id'), name='unique_company_per_client_tax_id'),
        ),
    ]
