# Generated by Django 6.0.3 on 2026-03-13 17:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_approved_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='rectified_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rectifications', to='documents.document'),
        ),
    ]
