# Generated by Django 6.0.1 on 2026-02-12 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_company_unique_company_per_client_tax_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='provider_name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='provider_tax_id',
        ),
    ]
