# Generated by Django 6.0.3 on 2026-03-13 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_document_rectified_at_document_rectified_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='rectified_document',
        ),
    ]
