# Generated by Django 6.0.1 on 2026-02-12 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_provider_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='flow',
            field=models.CharField(choices=[('in', 'Compra'), ('out', 'Venta'), ('unknown', 'Por revisar')], default='in', max_length=20),
        ),
    ]
