# Generated by Django 6.0.1 on 2026-02-13 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('documents', '0006_alter_document_flow'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='company',
            name='unique_company_per_client_tax_id',
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Factura'), ('delivery', 'Albarán'), ('corrected_invoice', 'Abono')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='review_level',
            field=models.CharField(choices=[('auto', 'Aprobado automáticamente'), ('manual', 'Manual'), ('recommended', 'Revisión recomendada'), ('required', 'Revisión requerida')], default='required', max_length=20),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['client', 'tax_id'], name='documents_c_client__21289e_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['client', 'name'], name='documents_c_client__daf9b1_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(condition=models.Q(('tax_id__isnull', False)), fields=('client', 'tax_id'), name='unique_company_per_client_tax_id'),
        ),
    ]
