# Generated by Django 6.0.1 on 2026-02-13 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_remove_company_unique_company_per_client_tax_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='tax_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
