# Generated by Django 6.0.3 on 2026-03-16 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_document_amount_snapshot_document_is_current_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='rectifications',
        ),
    ]
