# Generated by Django 6.0.3 on 2026-03-17 19:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('documents', '0009_remove_document_rectifications'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='document',
            constraint=models.UniqueConstraint(condition=models.Q(('is_current', True)), fields=('parent_document',), name='unique_current_version_per_document'),
        ),
    ]
