# Generated by Django 6.0.1 on 2026-02-18 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_alter_document_rejected_by'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='invoice_number',
            new_name='document_number',
        ),
    ]
