# Generated by Django 6.0.1 on 2026-02-24 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_document_approved_by_document_archived_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='flow',
            field=models.CharField(choices=[('in', 'Ingreso (venta)'), ('out', 'Gasto (compra)'), ('unknown', 'Por revisar')], default='in', max_length=20),
        ),
    ]
