# Generated by Django 6.0.1 on 2026-02-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_alter_document_flow'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_customer',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='is_provider',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
