# Generated by Django 6.0.1 on 2026-02-25 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_company_is_customer_company_is_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='type',
        ),
    ]
