# Generated by Django 6.0.1 on 2026-02-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0015_remove_company_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='flow',
            field=models.CharField(choices=[('in', 'Ingreso (venta)'), ('out', 'Gasto (compra)'), ('unknown', 'Por revisar')], db_index=True, default='in', max_length=20),
        ),
    ]
