# Generated by Django 6.0.1 on 2026-03-04 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_alter_document_flow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('invoice', 'Factura'), ('delivery', 'Albarán'), ('corrected_invoice', 'Factura rectificativa'), ('delivery_credit_note', 'Abono de albarán')], max_length=20),
        ),
    ]
